import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" type="text/css" href="../styles/globals.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <img class='background' src="https://www.rionegro.com.ar/wp-content/uploads/2022/12/19-12-2022_doha_argentina_se_consagro_campeon-1.jpg?w=920&h=517&crop=1"/>
        </div>
      </main>
    </>
  )
}
